name: Feature request
description: Suggest an improvement for onboarding or processes
title: "proposal: "
labels: ["proposal"]
body:
  - type: textarea
    attributes:
      label: What do you want to improve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is it important?
    validations:
      required: true
